# This file can be used to customize tox tests as well as other test frameworks like flake8 and mypy

[tox]
envlist = py38
; envlist = py37, py38, py39
isolated_build = true
skip_install = false

[testenv]
deps =
    pytest
    black
    flake8
    pydocstyle
    mypy
    isort
    types-requests

commands =
    pip install -e .
    pytest
    black --check tap_sumologic/
    flake8 tap_sumologic
    pydocstyle tap_sumologic
    mypy tap_sumologic --exclude='tap_sumologic/tests'

[testenv:pytest]
# Run the python tests.
# To execute, run `tox -e pytest`
envlist = py37, py38, py39
deps =
    pytest
commands =
    pip install -e .
    pytest

[testenv:format]
# Attempt to auto-resolve lint errors before they are raised.
# To execute, run `tox -e format`
deps =
    black
    isort
commands =
    pip install -e .
    black tap_sumologic/
    isort tap_sumologic

[testenv:lint]
# Raise an error if lint and style standards are not met.
# To execute, run `tox -e lint`
deps =
    black
    flake8
    pydocstyle
    mypy
    isort
    types-requests
commands =
    pip install -e .
    black --check --diff tap_sumologic/
    isort --check tap_sumologic
    flake8 tap_sumologic
    pydocstyle tap_sumologic
    # refer to mypy.ini for specific settings
    mypy tap_sumologic --exclude='tap_sumologic/tests'

[flake8]
ignore = W503
max-line-length = 88
max-complexity = 10

[pydocstyle]
ignore = D105,D203,D213,D406,D407,D107,D104
